# .github/workflows/main-cicd.yml
name: Main CI/CD Pipeline to AKS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  # 1. Call the workflow to build and push the Docker image to ACR
  build_and_push_acr:
    uses: ./.github/workflows/build-push-acr.yml # Path to the callable workflow
    # Pass necessary secrets to the called workflow
    secrets: inherit # Inherit all secrets available to this workflow

  # 2. Call the workflow to deploy the image to AKS
  deploy_to_aks:
    needs: build_and_push_acr # This job depends on the previous one completing successfully
    uses: ./.github/workflows/aks-deploy.yml # Path to the callable workflow
    with:
      # Pass outputs from the 'build_and_push_acr' job of the *previous workflow call*
      image_tag: ${{ needs.build_and_push_acr.outputs.full_acr_image_tag }}
      package_name: ${{ needs.build_and_push_acr.outputs.package_name }}
      package_version: ${{ needs.build_and_push_acr.outputs.package_version }}
    # Pass necessary secrets to the called workflow
    secrets: inherit # Inherit all secrets available to this workflow