apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-react-project-example
  namespace: dev  # Replace with your actual namespace
  labels:
    app: nexus-react-project-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexus-react-project-example
  template:
    metadata:
      labels:
        app: nexus-react-project-example
        azure.workload.identity/use: "true" 
    spec:
      serviceAccountName: keyvault-workload-sa
      containers:
      - name: nexus-react-project-example
        image: nexusacr20250625.azurecr.io/nexus-react-project-example:dev  # Replace with your actual image
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        volumeMounts:
        - mountPath: /mnt/secrets-store
          name: secret-volume
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
      volumes: 
      - name: secret-volume
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: nexus-keyvault