name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get package name and version from package.json
        id: package_info_step # Give this step an ID to access its outputs
        run: |
          PACKAGE_NAME=$(jq -r '.name' package.json)
          PACKAGE_VERSION=$(jq -r '.version' package.json)
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag "${{ secrets.DOCKER_USERNAME }}"/"${PACKAGE_NAME}":"${PACKAGE_VERSION}"
      - name: Push the Docker image   
        run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker push "${{ secrets.DOCKER_USERNAME }}"/"${PACKAGE_NAME}":"${PACKAGE_VERSION}"