name: CI/CD Pipeline

on:
  push:
    branches: ["feat/add-ci", "develop"]
  pull_request:
    branches: ["feat/add-ci"]

jobs:
  # Call the build workflow
  build:
    uses: ./.github/workflows/build.docker.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write

  # Deploy to AKS after successful build
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.acr.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
