name: CI/CD Pipeline

on:
  push:
    branches: ["feat/add-ci", "develop"]
  pull_request:
    branches: ["feat/add-ci"]

jobs:
  call-full-pipeline:
    name: Run Full CI/CD Pipeline
    uses: Nexus-Team-Project/nexus-react-project-example/.github/workflows/main.yml@feat/build-basic-ci
    secrets: inherit

